// <auto-generated />
using Animals_Nourish_Product.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animals_Nourish_Product.Migrations
{
    [DbContext(typeof(Animals_Nourish_ProductContext))]
    [Migration("20231015174819_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Animals_Nourish_Product.Model.Product", b =>
                {
                    b.Property<int>("Id_Product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Animal_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_Product")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Food_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name_Product")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price_Product")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Product");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
